// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2sNeA3hUnNAUDpBAlui3qnxUiHqbgP7Y',
    appId: '1:892737690470:web:7481ef886f8424239dc6a7',
    messagingSenderId: '892737690470',
    projectId: 'chilled-ee40a',
    authDomain: 'chilled-ee40a.firebaseapp.com',
    storageBucket: 'chilled-ee40a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDHf1JYFMr1S4665Tp3v1XrQ4bEUOjSnA',
    appId: '1:892737690470:android:a6b113e7ea3a00f29dc6a7',
    messagingSenderId: '892737690470',
    projectId: 'chilled-ee40a',
    storageBucket: 'chilled-ee40a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJSV27yI62VO3Or7Bs9gixH6UQ6iNnGYs',
    appId: '1:892737690470:ios:50afa8700498b0699dc6a7',
    messagingSenderId: '892737690470',
    projectId: 'chilled-ee40a',
    storageBucket: 'chilled-ee40a.appspot.com',
    iosBundleId: 'com.example.chilled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJSV27yI62VO3Or7Bs9gixH6UQ6iNnGYs',
    appId: '1:892737690470:ios:50afa8700498b0699dc6a7',
    messagingSenderId: '892737690470',
    projectId: 'chilled-ee40a',
    storageBucket: 'chilled-ee40a.appspot.com',
    iosBundleId: 'com.example.chilled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2sNeA3hUnNAUDpBAlui3qnxUiHqbgP7Y',
    appId: '1:892737690470:web:ed9602df9a56e4d39dc6a7',
    messagingSenderId: '892737690470',
    projectId: 'chilled-ee40a',
    authDomain: 'chilled-ee40a.firebaseapp.com',
    storageBucket: 'chilled-ee40a.appspot.com',
  );
}
